---
title: "Modelos de conectividad de grupos funcionales de aves en la GAM"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    social: menu
    source: embed
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(esri2sf)

#--------------- URL de geoservicios --------------

url_agfs_bosque_bripario <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_parches_esenciales_importantes_bosque_bripario/FeatureServer/0"

url_agfs_limite_gam <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_gam/FeatureServer/0"

#---------------------- Datos ---------------------

# Objetos sf

# Bosque y bosque ribereño
sf_bosque_bripario <- esri2sf(url_agfs_bosque_bripario)

# Límite de la GAM
sf_limite_gam <- esri2sf(url_agfs_limite_gam)

#---------------- Paletas de colores ---------------

# Paletas de colores
pal_bosque_bripario_d_PC <- 
  colorNumeric(
    palette = "Blues", 
    domain = sf_bosque_bripario$d_PC
  )
pal_bosque_bripario_IF <- 
  colorNumeric(
    palette = "Blues", 
    domain = sf_bosque_bripario$IF_
  )
```

### Bosque y bosque ribereño

```{r}
leaflet() %>%
  setView(-84, 9.95, 10) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen, group = "Stamen") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_gam,
    fillOpacity = 0.3,
    stroke = TRUE,
    weight = 0.5,
    smoothFactor = 0.2,
    group = "Límite de la GAM"
  ) %>%
  addPolygons(
    data = sf_bosque_bripario,
    fillOpacity = 0.9,
    stroke = TRUE,
    color = ~pal_bosque_bripario_d_PC(d_PC),
    fillColor = ~pal_bosque_bripario_d_PC(d_PC),
    weight = 0.3,
    smoothFactor = 0.2,
    group = "Parches esenciales"
  ) %>%
  addLegend(
    position = "bottomright",
    pal=pal_bosque_bripario_d_PC,
    values = sf_bosque_bripario$d_PC, 
    group = "Parches esenciales",
    title = "Esencialidad"
  ) %>%    
  addPolygons(
    data = sf_bosque_bripario,
    fillOpacity = 0.9,
    stroke = TRUE,
    color = ~pal_bosque_bripario_IF(IF_),
    fillColor = ~pal_bosque_bripario_IF(IF_),
    weight = 0.3,
    smoothFactor = 0.2,
    group = "Parches importantes"
  ) %>%
  addLegend(
    position = "bottomright",
    pal=pal_bosque_bripario_IF,
    values = sf_bosque_bripario$IF_, 
    group = "Parches importantes",
    title = "Importancia"
  ) %>%    
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen", "Imágenes de ESRI"),
    overlayGroups = c("Límite de la GAM", "Parches esenciales", "Parches importantes"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$OpenStreetMap.Mapnik
  ) %>%
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  hideGroup("Parches esenciales") %>%
  hideGroup("Parches importantes")
```

***
**Direcciones de los geoservicios**

[Parches esenciales](https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_parches_esenciales_importantes_bosque_bripario/FeatureServer/0)  

[Parches importantes](https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_parches_esenciales_importantes_bosque_bripario/FeatureServer/0)
